### PR TITLE
YOLO: Ensure files don't start with newlines

### PR DESCRIPTION
**Pull request by akx**
Sometimes, depending on chance, either train.txt or test.txt could start with a newline, which breaks Darknet, as it attempts to load a file called `''`.

So, instead of tracking whether we've started an export at all, track whether we've written anything to these files.

(To be honest, I think an exporter API that didn't use `fs.appendFile` to open-append-close the files would be better, but that would require adding a "finalize" call of some sort.)

This was reported by @moonq.

### CODE REVIEW

**Comment by aribornstein** [comment]
Will review and merge if clean this weekend thanks so much for actively participating :)

**Comment by moonq** [comment]
fyi another bug: if you export YOLO from a Video, the test.txt and
train.txt do not have newlines _at all_

**Comment by aribornstein** [comment]
Okay will validate and post by the end of the week.

**Comment by aribornstein** [comment]
Looks good. Merging

**Pull request merged**
